### ISSUE TITLE
After Elgato Stream Deck Update -> cant connect to Homebridge

### ISSUE THREAD

**Issue by KahJottUh** [sergey-tihon/streamdeck-homebridge#14]
Yesterday i updated the Elgato Stream Deck software. Then the Homebridge Plugin doesn't connect anymore with the Homebridge Server.

IP:Port / username / password  are correct. With any Browser i can login.
I deinstalled the plugin and reinstalled it. Doesn't changed the issue that the stream deck plugin can't login.
![homebridge](https://user-images.githubusercontent.com/45134923/202161106-46952db4-1a8d-4ab7-8e48-97153621a072.jpg)

I really hope anyone can help me. Because i like this plugin so much and use it so often during the day.

**Comment by sergey-tihon** [comment]
What version of Homebridge do you have?

Just tested with latest `Stream Deck software` and everything works fine for me.

**Comment by KahJottUh** [comment]
Thank you very much for your respond.
I am glad that this isnt just on my side. I can't open the link you embedded, so I dont really know what the problem is.

But I hope this will be fixed soon. 
So if I understand correctly, the Update causes the problem and can only be solved on the side of Elgato ?

Again thank you very much, now I know i can't do anything besides waiting :)

**Comment by sergey-tihon** [comment]
> So if I understand correctly, the Update causes the problem and can only be solved on the side of Elgato ?

Yes, the simplest possible fix is on the Elgato side.

If you interested in technical details:
- Most of cross-platform StreamDeck plugins are written in JS
- StreamDeck runs JS code inside Qt / QWebEngineView 
- Elgato migrated from `Qt 5` to `Qt 6` what also increase [Chromium version](https://wiki.qt.io/QtWebEngine/ChromiumVersions)
- Newer Chromium has different defaults and enforce CORS check on HTPP calls
- All JS plugins that calls 3rd party API to get some data are broken, because API servers don't allow calls from `file://..` urls
- The easiest fix (probably) is [turn off CORS for QWebEngineView](https://forum.qt.io/topic/132956/qwebengineview-javascript-fetch-cors-error-but-works-on-chrome-desktop). The other option is to provide a workaround and wait months till all plugin authors update their plugins.

**Comment by sergey-tihon** [comment]
@KahJottUh you may try StreamDeck 6.0.1. It should fix the issue

**Stream Deck 6.0.1**
⬇️ Download
macOS: https://edge.elgato.com/egc/macos/sd/Stream_Deck_6.0.1.17713.pkg
Windows: https://edge.elgato.com/egc/windows/sd/Stream_Deck_6.0.1.17713.msi

**Comment by KahJottUh** [comment]
Hello @sergey-tihon ,
Thank you very much for keeping me updated. This unofficial update fixed the issue and now it is working amazing again. :D 
I am so happy right now.

I have a basic understanding about coding. (20 years ago I learned php for designing websites as a hobby) So that you addressed the problem helped me a bit to understand what was going on. 

And now you provided a link of an unofficial update, which now helped solving the problem.

You are a very competent coder and your plugin is one of the best for the stream deck.
Thank you very much for your work and keep your spirit, i like that.

I wish you all the best and have a great day. For myself I can say today is a great day :)

Regards
Sebastian
