### ISSUE TITLE
Crashes in Stream Deck v6.0.[0,1]

### ISSUE THREAD

**Issue by andypiper** [sergey-tihon/streamdeck-homebridge#15]
Unfortunately, I'm finding that this plugin is causing the new Stream Deck v6 software to report errors via the QtWebEngineProcess when the button is clicked on to configure it in preferences. I was previously using it successfully to open the Homebridge UI but now cannot configure it (and the existing button icon on the physical Stream Deck reports a ⚠️ when the button is pressed).

Running Stream Deck 6.0.1 on macOS Ventura / Apple Silicon.

**Comment by sergey-tihon** [comment]
> Stream Deck v6 software to report errors via the QtWebEngineProcess when the button is clicked on to configure it in preferences.

Can you share this error?

> I was previously using it successfully to open the Homebridge UI but now cannot configure it

Did you use it with the same accessory that you configure now?

> existing button icon on the physical Stream Deck reports a ⚠️ when the button is pressed

This may be part of the behaviour of this plugin.

https://github.com/sergey-tihon/streamdeck-homebridge/blob/main/src/StreamDeck.Homebridge/PluginAgent.fs#L54-L56

- You press the button
- The plugin sends a request to Homebridge and asks to change the characteristic to some target state (opposite to current, like on/off)
- Homebridge delegate this request to Homebridge plug that actually processes it and communicate with the device.
- When Homebridge replies, the plugin sends one more request to Homebridge and asks for the current value of the configured characteristic.
- If the plugin sees the same value as before (the server reports the same state), the plugin show ⚠️ on the button.

⚠️ may be an expected behaviour of the this plugin, when something wrong with installed Homebridge plugin or accessory.

**Comment by ju93m** [comment]
Hey there, ive the same error and can share at the first lines of error code if its helpful 

 

> -------------------------------------
> Translated Report (Full Report Below)
> -------------------------------------
> 
> Process:               QtWebEngineProcess [1750]
> Path:                  /Applications/Elgato Stream Deck.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/A/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
> Identifier:            org.qt-project.Qt.QtWebEngineProcess
> Version:                ()
> Code Type:             ARM-64 (Native)
> Parent Process:        Stream Deck [860]
> Responsible:           Stream Deck [860]
> User ID:               501
> 
> Date/Time:             2022-11-26 14:59:47.6236 +0100
> OS Version:            macOS 13.0.1 (22A400)
> Report Version:        12
> Anonymous UUID:        B8E63671-E09F-E105-6F3D-A7FD9CF166BC
> 
> 
> Time Awake Since Boot: 610 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0  CrRendererMain  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BREAKPOINT (SIGTRAP)
> Exception Codes:       0x0000000000000001, 0x0000000117cfb050
> 
> Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
> Terminating Process:   exc handler [1750]
> 
> Kernel Triage:
> VM - pmap_enter retried due to resource shortage
>

**Comment by sergey-tihon** [comment]
@ju93m thank, but how you understand that it is related with this plugin? 

From shared log I see that Elgato process that host plugins crash on ARM-64 with no details what happened or what caused the error.

**Comment by ju93m** [comment]
@sergey-tihon you're welcome, i think its issued by this plugin because it appears when i try to use a button related to the plugin. It's the same scenario as @andypiper describes in his post. Is there any possibility to assist in solving that issue?

**Comment by andypiper** [comment]
I'm no longer certain that this is related to the plugin - apologies to @sergey-tihon here!

Initially it seemed to stop once I had removed the Homebridge plugin (and I was unable to configure the plugin if it was installed), but now it has come back and I'm still seeing the Qt error from Elgato.

So I am going to close this out as I am not able to pinpoint a connection between the plugin and the error - I think the Stream Deck v6 update (or, another plugin) is more likely to be the problem.

Again, @sergey-tihon apologies for not having done enough checking on my side - and thank you for your work on homebridge-streamdeck! 🙏🏻

**Comment by sergey-tihon** [comment]
@ju93m This plugin is JS one, that run inside QtWebEngineProcess (or basically browser). It is isolated environment, JS code should not be able to crush the browser - it is bug and serious vulnerability by its own, that should be fixed on the host side Qt/Elgato.

If you cannot share full log here you can contact Elgato support with this case. Would be really nice to fix root cause of this crush.
